### PR TITLE
fix typos and update macOS name

### PR DESCRIPTION
**Pull request by McSinyx**

### CODE REVIEW

**Comment by oetiker** [comment]
thanks!

**Comment by oetiker** [comment]
sure :) can you please make a PR ?

**Comment by souvlakeeb** [comment]
I believe this change was made in error:

https://github.com/oetiker/lshort/pull/3/commits/655c41bdf30256e69be0c1fb17313065d1b09a70#diff-898de0960860f2d8c94f3dcc258caacee1e1baaf0bb99f73cd75039f4b192ae2L1030

**Comment by McSinyx** [comment]
```diff
diff --git a/book/src/typeset.tex b/book/src/typeset.tex
index 7038bef..a085b5b 100644
@@ -1027,7 +1032,7 @@ \subsubsection{It's all $\Gamma\rho\epsilon\epsilon\kappa$ to me}
 \verb|\text|\emph{language} command:
 
 \begin{lscommand}
-\verb|Englisch text. \textgerman{Gesundheit} is actually a German word.|
+\verb|English text. \textgerman{Gesundheit} is actually a German word.|
 \end{lscommand}
 
 This may look unnecessary since the only advantage is a correct hyphenation,
```

You mean this one, @souvlakeeb?  Looking at the surrounding text it seems the German mixin wasn't intentional.  Either way, I think that part was rewritten some time ago and is no longer present in (now) `src/realworld.tex`.

**Pull request merged**
