### PR TITLE
Add contributing guide

### PR DESCRIPTION
**Pull request by marcin-serwin**
I've added some contributing guidelines as discussed [previously](https://github.com/oetiker/lshort/pull/54#discussion_r944259255). If these guidelines are accepted I'll update this pull request with commits that apply them throughout the book (other PRs should be merged before that to avoid merge conflicts).

### CODE REVIEW

**Comment by oetiker** [comment]
@rmrstar any input re the language section?

**Comment by rmrstar** [comment]
@oetiker 'the language section', meaning the ##Text section?
Not really, although a large part of the document is currently in English English. 
Should there be a rule about trailing whitespace on a source line? I now see my editor has stripped it from some of the TikZ drawing commands. I don't think this matters, but is there a situation where it does?

**Comment by oetiker** [comment]
@rmrstar white space at the end of lines should be stripped, yes.

And yes the ##text section. @marcin-serwin and I were discussiong to switch everyting over to american english as it is more widely used.

**Comment by rmrstar** [comment]
Some observations to the end of chapter 1.

1. While mostly in English, the document already uses 'different than', which is American.
2. There's a mixture of single and double quotes (\enquote, \enquote*), even within paragraphs. Is there a rule?
3. Sometimes it's word\ldots, at others word <space> \ldots.
4. There are (illusionary?) formatting inconsistencies in the use of (e.g.) 'WYSIWYG' vs '\wi{WISIWYG}', or \eei{.dvi} vs \texttt{.pdf}. A guide to these formatting commands might be useful.
5. Some sentences end in a displaymath or code environment, or similar. Some of those have their full-stops, others don't. I realise this is a difficult thing at times.

6. Incidentally, I'm finding the light-green bibliography reference numbers (hyperlinks) difficult to read against the white background.

**Comment by oetiker** [comment]
> Some observations to the end of chapter 1.
> 
>     1. While mostly in English, the document already uses 'different than', which is American.

+1 for going american
 
>     2. There's a mixture of single and double quotes (\enquote, \enquote*), even within paragraphs. Is there a rule?

there is no rule (yet) :)

>     3. Sometimes it's word\ldots, at others word  \ldots.

hmm, my intuition would be to leave a space ...

>     4. There are (illusionary?) formatting inconsistencies in the use of (e.g.) 'WYSIWYG' vs '\wi{WISIWYG}', or \eei{.dvi} vs \texttt{.pdf}. A guide to these formatting commands might be useful.

the commands not only format, they also add the words to the index

>     5. Some sentences end in a displaymath or code environment, or similar. Some of those have their full-stops, others don't. I realise this is a difficult thing at times.

please advise :)

>     6. Incidentally, I'm finding the light-green bibliography reference numbers (hyperlinks) difficult to read against the white background.

I think we have not yet configured the pdf link colors ... @marcin-serwin ?

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
lets have this in ... can be improved and PRd as we go along

**Pull request merged**
